var movies = [{
    title: 'The Nativity Story',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/89-the-nativity-story.jpg',
    plot: 'From the director of Twilight comes the greatest, and most repeated, story ever told. Catherine Hardwicke&#39;s version of the Nativity is a little on the ho-hum side, straightforward and glossy, but her Thirteen instincts have her playing up the &ldquo;teen pregnancy&rdquo; angle, making the film palatable in the modern age.',
    release: 1900,
    rating: 0,
}, {
    title: 'Jack Frost',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/90-jack-frost.jpg',
    plot: 'A magical harmonica brings rock star Jack Frost (Michael Keaton) back from the dead to inhabit the body of a snowman. Which is creepy as all hell &mdash; and a little sweet.',
    release: 1990,
    rating: 0,
}, {
    title: 'I&#39;ll Be Home for Christmas',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/91-ill-be-home-for-christmas2.jpg',
    plot: 'Better appreciated as a relic of the Jonathan Taylor Thomas era than as a holiday treat, Disney&#39;s Christmas road movie offers the right kind of silliness for early December viewing (before the hardcore marathoning begins). Who doesn&#39;t love the Santa 5K?',
    release: 1990,
    rating: 0,
}, {
    title: 'Santa&#39;s Slay',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/92-santas-slay2.jpg',
    plot: 'After 1,000 years of delivering presents, a disgruntled Santa goes postal. The 2005 movie opens with the subversive notion of Kris Kringle murdering Jews and spirals down from there. Just not as weird as it could have been, oddly enough.',
    release: 1990,
    rating: 0,
}, {
    title: 'The Perfect Holiday',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/93-The-Perfect-Holiday.jpg',
    plot: 'Dredged from the bottom of the generic romantic comedy gutter, Morris Chestnut plays an aspiring musician working as a mall Santa who falls for Gabrielle Union. That&#39;s it. There are angels, to ensure the Christmas stamp of approval.',
    release: 1990,
    rating: 0,
}, {
    title: 'The Family Man',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/94-the-family-man.jpg',
    plot: 'Brett Ratner teams up with Nicolas Cage for his own twist on the It&#39;s a Wonderful Life model. Saccharine beyond comprehension and a gingerbread cookie cutter script makes this acceptable, but never required holiday viewing.',
    release: 1990,
    rating: 0,
}, {
    title: 'Santa Claus: The Movie',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/95-santa-claus-the-movie.jpg',
    plot: 'This movie sounds like gold on paper: A Santa Claus mythos story decorated like the Superman franchise. The film has the sheen of the superheroic franchise, but little of the heart.',
    release: 1990,
    rating: 0,
}, {
    title: 'Four Christmases',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/96-%20four-christmases.jpg',
    plot: 'Oh hey, another Vince Vaughn Christmas movie feels more like a chore for the holiday completist than a dose of cheer. Four Christmases is Reese Witherspoon&#39;s Sweet Home Alabama act transplanted to December and loaded with stars (Dwight Yoakam!) and yet, it&#39;s a total bust. Vince Vaughn may not be cut out for the &ldquo;nice&rdquo; list.',
    release: 1990,
    rating: 0,
}, {
    title: 'Fred Claus',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/97-fred-claus.jpg',
    plot: 'Meet the Parents director David Dobkins throws millions at the screen to bring Santa&#39;s workshop to life, even recruiting the perfect modern actor, Paul Giamatti, to the play the big guy. And then Vince Vaughn shows up to be a cynical asshole and ruin it.',
    release: 1990,
    rating: 0,
}, {
    title: 'Santa with Muscles',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/98-santa-with-muscles.jpg'
    plot: '	Starring Hulk Hogan as a millioniare-bodybuilder-turned-amnesiac-mall-Santa-crime-fighter, Santa with Muscles is a bonkers Christmas adventure that might have been better as a Yahoo Serious vehicle. Maybe.',
    release: 1990,
    rating: 0,
}, {
    title: 'Christmas with the Kranks',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/99-christmas-with-the-kranks.jpg',
    plot: 'Awful people celebrate Christmas too, you know! Based on a novel by John Grisham, the quality of this Tim Allen/Jamie Lee Curtis comedy depends mostly on one&#39;s tolerance for oafish comedy and the manufactured elements of the holiday.',
    release: 1990,
    rating: 0,
}, {
    title: 'All I Want for Christmas',
    image: image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/100-all-i-want-for-christmas2_0.jpg',
    plot: 'It&#39;s like House Arrest, but with all of the charm replaced by tinsel. Not based on the Mariah Carey song (but maybe it would have been better if it had been?). Worth one viewing for Leslie Nielsen as &ldquo;Santa.&rdquo;',
    release: 1990,
    rating: 0,
} {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/87-the-nutcracker.jpg',
    title: 'The Nutcracker',
    plot: 'George Balanchine&#39;s Nutcracker ballet is a treasured work of holiday culture. The movie version starring Macaulay Culkin is not.',
    release: 1993,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/86-a-christmas-carol.jpg',
    title: 'A Christmas Carol',
    plot: 'Thanks to the magic of motion capture animation, Jim Carrey was able to play Ebenezer Scrooge at every age and all three of the visiting Ghosts. That didn&#39;t really add anything, but it&#39;s fun to say that. The highlight here is the film&#39;s frightening tone. Director Robert Zemeckis wanted to turn the spirit-filled tale into a certified ghost story.',
    release: 2009,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/85-prancer.jpg',
    title: 'Prancer',
    plot: 'The sad part about Prancer is that if a little ginger girl really started whining about how she had a flying reindeer in the barn, everyone would brush her off. Super annoying. Prancer aims for the E.T. magic and woefully misses the mark, enough to earn it some nostalgia points.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/84-surviving-christmas3.jpg',
    title: 'Surviving Christmas',
    plot: 'The not-as-awful-as-they-say-but-still-kinda-stupid Christmas movie from 2004 piles on way too many lame gags, but a genuine relationship breaks through. Ben Affleck and James Gandolfini are good fun as a wayward Christmas hater and his stand-in father figure. It&#39;s sadistic and ugly, but at least it&#39;s going for something.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/83-santa-claus-conquers-the-martians.jpg',
    title: 'Santa Claus Conquers the Martians',
    plot: 'Pure yuletide shlock that&#39;s completely unaware of its ineptitude. Santa is kidnapped by Martians, meets a flailing robot (clearly made of cardboard boxes), and teaches the Martians how to hold their own Christmas. Great for those eggnog-fueled evenings that blow past 2 a.m.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/82-angels-sing.jpg',
    title: 'Angels Sing',
    plot: 'Harry Connick Jr. emits a strange aura capable of transmuting the horrors found in ABC Family movies into watchable melodramatic, corny fluff. Angels Sing pairs Connick Jr. with the likes of Willie Nelson and Kris Kristofferson for a film that&#39;s basically a warm and fuzzy group sing in movie form (while also including a sing-a-long scene).',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/81-friday-after-next.jpg'
    title: 'Friday After Next'
    plot: 'Craig (Ice Cube) and Day-Day (Mike Epps) returned for a third Friday movie that was almost exactly like the other two Friday movies except it took place during Christmas. Some criminal activity, some major partying, some wacky antics around the neighborhood. Standard issue and watchable.'
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/80-jingle-all-the-way.jpg'
    title: 'Jingle All the Way'
    plot: 'Arnold Schwarzenegger&#39;s holiday entry seemed like a ridiculous farce in 1996. &ldquo;Shopping would never get that crazy!&rdquo; Wrong. Like a fine wine, time transformed Jingle All the Way into a frightening reflection of modern consumerism complete with the walking, talking Anakin Skywalker action figure.'
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/79-bush-christmas2.jpg',
    title: 'Bush Christmas',
    plot: 'This Australian film is cut from the Disney cloth &mdash; think Swiss Family Robinson or Homeward Bound. It has very little do with Christmas and lots to do with rescuing horses from mean ol&#39; thieves. Which, turns out, is pretty fun in the Australian outback.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/78-the-holiday.jpg'
    title: 'The Holiday'
    plot: 'A Christmas movie was inevitable for &ldquo;white people problems&rdquo; connoisseur Nancy Meyers. The fact that she tapped the holidays to draw out one of Jack Black&#39;s best (and undervalued) performances is the real surprise.'
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/77-lethal-weapon.jpg'
    title: 'Lethal Weapon'
    plot: 'Great buddy comedy, pretty good Christmas movie. There isn&#39;t a ton of Christmas cheer in Richard Donner&#39;s whacked out (read: costarring Gary Busey) action flick, but kicking things off with &ldquo;Jingle Bell Rock&rdquo; sets the mood just right.'
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/76-babes-in-toyland2.jpeg',
    plot: 'Babes in Toyland',
    plot: 'A Technicolor update to the 1934 film, fit snuggly into the Disney musical mold. The late Annette Funicello stars in the Babes remake, that feels more like a testing ground for Mary Poppins or Chitty Chitty Bang Bangthen it&#39;s own spectacle',
    release: 1961,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/75-ernest-saves-christmas.jpg',
    title: 'Ernest Saves Christmas',
    plot: 'You&#39;re either in or your out when it comes to Jim Varney&#39;s bumbling, yokel funnyman Ernest P. Worrell. He&#39;s dumb, but loving &mdash; the perfect Christmas movie character. Here, he saves the day for Santa',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/74-beyond-tomorrow2.jpg',
    title: 'Beyond Tomorrow',
    plot: 'One Christmas Eve, three businessmen decide to see what happens when they throw their wallets out the window. A nice gal returns it, earning their admiration. They later die, return as ghosts, and help her fall in love and &ndash; oh my god this movie is weird.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/73-it-happened-on-5th-avenue.jpg',
    title: 'It Happened On 5th Avenue',
    plot: 'The story of a millionaire family who discovers a homeless person living in their Fifth Avenue pad. Unbelievable by today&#39;s standards, where the vagrant would be arrested and hauled away to prison for all eternity. Times change, but that gives makes this movie pleasantly goofy.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/72-reindeer-games.jpg',
    title: 'Reindeer Games',
    plot: 'John Frankenheimer&#39;s final film is a twisty, turny journey down holiday road, with a manic Ben Affleck in the driver&#39;s seat. Full of weird angles, snappy language, and sadistic humor, the movie has gone unappreciated since it debuted to horrid reviews in 2000.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/71-santa-clause-2.jpg',
    title: 'The Santa Clause 2: The Mrs Clause',
    plot: 'Progressive thinking has never been one of Christmas movies&#39; strongest suits, so it&#39;s no surprise the sequel to Tim Allen&#39;s Santa Clause involved the ticking-clock search for a Mrs. But the film is a sweet romance between Allen and Elizabeth Mitchell, so the archaic thinking is easy to overlook.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/70-trapped-in-paradise.jpg',
    title: 'Trapped in Paradise',
    plot: 'Christmas cheer has a gravitation force. In Trapped in Paradise, bank robbing brothers, Nicolas Cage, Jon Lovitz, and Dana Carvey, can&#39;t escape it&#39;s power. It&#39;s almost like Groundhog Day minus the supernatural element and even more holidayisms.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/69-unaccompanied-minors.jpg',
    title: 'Unaccompanied Minors',
    plot: 'Based on a This American Life segment, pre-Bridesmaids Paul Feig wrote and directed this holiday movie about a group of kids trapped in an airport. Hijinks and bonding ensue.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/68-the-christmas-that-almost-wasnt.jpg',
    title: 'The Christmas That Almost Wasn&#39;t',
    plot: 'Collide Goodbye, Mr. Chips with the shows of Sid &amp; Marty Kroft and out comes The Christmas That Almost Wasn&#39;t, an Italian-produced musical romp. What separates this movie from the imitators is its baddie, played by Italian director Rossano Brazzi (oddly, the nice guy star, Paul Tripp, wrote the movie). He could be just another Christmas-hating businessman, but he opts for a more Snidely Whiplash approach.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/67-the-polar-express.jpg',
    title: 'The Polar Express',
    plot: 'Despite soulless characters who look like walking, talking mall mannequins, Robert Zemecki&#39;s foray into motion capture animation is a whirlwind of imagination. Defying physics is the name of the game, while the artwork of illustrator/writer Chris Van Allsburg gives the movie a glowing appearance.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/66-just-friends2.jpg',
    title: 'Just Friends',
    plot: 'Best known for putting Ryan Reynolds in a fat suit, this easily thrown away romantic comedy hides hometown charm underneath its slapsticky gift wrap (although that&#39;s fun too). Evidence that Reynolds and Anna Faris should costar in every movie together.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/65-kiss-kiss-bang-bang2.jpg',
    title: 'Kiss Kiss, Bang Bang',
    plot: 'Shane Black, writer of Lethal Weapon, returns with another Christmas-ish movie, this time a meta-noir starring the quick-witted Robert Downey Jr.. Instead of fueling the plot, Christmas drives the action &mdash; RDJ even does a bit of &ldquo;shopping&rdquo; early on.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/64-2.jpg',
    title: 'How the Grinch Stole Christmas',
    plot: 'Before the days of motion capture, Ron Howard padded Jim Carrey with actual makeup to play Dr. Seuss&#39; furry, green bastard. It&#39;s an ideal role for Carrey, whose bravado can prevail through the Seussian facade. Howard doesn&#39;t have anything new to add, but seeing it realized is a wonder all its own.',
    release: 2000,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/63.png',
    title: 'One Magic Christmas',
    plot: 'The movie that made everyone wish Harry Dean Stanton was their guardian angel. Mary Steenburgen stars as a working class woman who loses her faith (OK, &ldquo;Christmas spirit&rdquo;) and revives it Christmas Carol-style. Or with the help of Santa, because it is a Disney movie, after all.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/62.jpeg',
    title: 'Mickey&#39;s Christmas Carol',
    plot: 'Fact: Mickey&#39;s Christmas Carol was nominated for the animated short film Oscar in 1983. And it&#39;s simply okay! I guess the folks at Disney felt they needed to embrace the Ebeneezer Scrooge/Scrooge McDuck crossover at some point.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/61.jpg',
    title: 'About a Boy',
    plot: 'A wry coming-of-age tale that remains one of Hugh Grant&#39;s few non-rom-com roles. About a Boy is quite touching amidst its Christmas backdrop, but works even more successfully as a launching pad for Badly Drawn Boy&#39;s holiday soundtrack.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/60.jpg',
    title: 'Batman Returns',
    plot: 'As if Bruce Wayne&#39;s life wasn&#39;t tortured enough, masochist Tim Burton posited how the superheroic millionaire would feel during Christmas. Or perhaps the snowy holiday was a quick way to enliven the gothic production design. Either way, audiences won.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/59.jpeg',
    title: 'A Very Harold &amp; Kumar Christmas',
    plot: 'It&#39;s a Christmas miracle that a third Harold &amp; Kumar is remotely watchable, let alone wildly entertaining. Why has Waffle-bot still not received a spin-off?',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/58.jpg',
    title: 'Susan Slept Here',
    plot: 'The &#39;50s: When a romantic comedy about an Academy Award-winning screenwriter falling in love with a 17-year-old vagrant put under house arrest in his swinging pad was perfectly socially acceptable. A sweet, Christmas love story for those who can look past the creepy twist.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/57.jpg',
    title: 'The Family Stone',
    plot: 'If The Family Stone is basically a Lars von Trier movie without the NC-17 moments of intimacy or genitalia mutilation. A family&#39;s worth &mdash; Diane Keaton, Craig T. Nelson, Dermot Mulroney, Sarah Jessica Parker, Luke Wilson, Claire Danes, Rachel McAdams &mdash; of life problems explode during the holidays. Even the deaf gay brother is all too believable.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/56.jpeg',
    title: 'TheBest Man Holiday',
    plot: 'A shockingly enjoyable sequel to the 1999 dramedy The Best Man wrangles the entire cast back for a hard R-rated holiday weekend. There&#39;s weed smoking, sex talk, terminal illness, and football. The movie does not skimp on the melodrama and it shouldn&#39;t &mdash; it&#39;s Christmas, after all.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/55.jpg',
    title: 'Scrooge',
    plot: 'Albert Finney sings and dances through the timeless Christmas story. His Ebenezer sings a song called &ldquo;I Hate People&rdquo; which everyone should learn the lyrics to in time for this year&#39;s Christmas dinner.',
    release: 1970,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/54.jpeg',
    title: 'The Ref',
    plot: 'You know who should have played the live-action Grinch? Dennis Leary. Fans of the raucous comedian can cherish The Ref, that dilutes Leary enough to teach his robber character a Christmas lesson.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/53.jpg',
    title: '3 Godfathers',
    plot: 'John Wayne plays one of the Three Wise Men in one of the few, respectable Christmas Westerns. John Ford brings the same grandiose touch to carols as he does shoot-outs and this is the rare movie features both.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/52.jpeg',
    title: 'Comfort and Joy',
    plot: 'Bill Forsyth&#39;s cheeky Scottish comedy follows a radio DJ caught in the middle of an ice cream truck turf war. Zany sounding? Star Bill Patterson keeps his cool while Forsyth implodes the world around him. It&#39;s a Very Murphy&#39;s Law Christmas.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/51.jpeg',
    title: 'Home Alone 2: Lost in New York',
    plot: 'Setting a Home Alone sequel anywhere but home sounds like an awful idea. Yet New York, a bustling Christmas metropolis, plays directly into everything that worked in the first movie. Toy shops and frightening old people and apartments that are so run down, they&#39;re basically booby trapped already',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/50.jpeg',
    title: 'The Little Drummer Boy',
    plot: 'One of the few Bible-inspired Rankin &amp; Bass films, The Little Drummer Boy tells the story of the Nativity from the perspective of the titular character. The film revealed the question everyone was dying to know: What was the Little Drummer Boy doing before he met Jesus?',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/49.jpeg',
    title: 'Mixed Nuts',
    plot: 'There&#39;s nothing wrong with unbridled comedy if it&#39;s in the right hands. Nora Ephron&#39;s Mixed Nuts is pure lunacy pulled off by Steve Martin and a cast who&#39;s ready to run the required race. Liev Schreiber deserved an Oscar for his transvestite dance moves.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/48.jpg',
    title: 'Rare Exports',
    plot: 'The Finnish people have an odd sense of humor. Only they would turn Santa into a demon creature who lives in the mountains and is bent on punishing little children and then turn around and make an exciting, multi-note film out of the concept.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/47.jpg',
    title: 'While You Were Sleeping',
    plot: 'A staple of early 2000s HBO programming, Sandra Bullock&#39;s romantic comedy of mismatched coma victims is staged against Christmas, adding to the pressure surrounding the big reveal (the guy who was hit by a train isn&#39;t her fianc&eacute;!).',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/46.jpg',
    title: 'Miracle on 34th Street',
    plot: 'The real gem of this rehash isn&#39;t Sir Richard Attenborough or Mara Wilson, as good as they are. It&#39;s Elizabeth Perkins, who adds wit and emotional damage to the mother character. Writer John Hughes is credited for many of the finest young adult scripts of the &#39;80s and &#39;90s, but the key was that he always nailed the parents.',
    release: 1994,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/45.jpg',
    title: 'The Man Who Came To Dinner',
    plot: 'Before there was You, Me, and Dupree, before there was Sinbad&#39;s Houseguest, there was The Man Who Came to Dinner. Monty Woolley plays a slimy radio personality who slips on some ice one Christmas and takes solace in a middle-class family&#39;s home. Woolley is the best kind of scumbag in this one, and the hysteria of Christmas acts as an echo chamber to his maniacal ways.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/44.jpg',
    title: 'Metropolitan',
    plot: 'That first year you come home from college to see your high school friends and everyone&#39;s different. That&#39;s why Metropolitan, a cultural essay more than a Christmas-themed movie, belongs on this list.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/43.jpeg',
    title: 'The Lemon Drop Kid',
    plot: 'Bob Hope is a riot as a con man raising cash during Christmas time by swindling Salvation Army donators. He nails it all: the quick wit, the physical comedy, the musical numbers (the movie introduced &ldquo;Silver Bells&rdquo;).',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/42.jpeg',
    title: 'White Christmas',
    plot: 'After 60 years, White Christmas, a musical scored by Irving Berlin, is fortified and tolerated as a Christmas classic. Will induce sleep if viewed after 6 P.M.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/41.jpeg',
    title: 'Scrooged',
    plot: '&ldquo;What if David Cronenberg directed A Christmas Carol?&rdquo; &quot;He&#39;s unavailable.&quot; &quot;We&#39;ll get Richard Donner.&quot; &ldquo;Eh, doesn&#39;t sound very enjoyable.&rdquo; &ldquo;OK, it&#39;ll be funny because we&#39;ll hire&#8230; Bill Murray!&rdquo;',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/40.jpg',
    title: 'Holiday Affair',
    plot: 'There are a lot of Christmas movies set in department stores. Perhaps because they were still shiny and new in the &#39;40s? Whatever the case, Holiday Affair is still a gem, Robert Mitchum playing a store clerk who loses his job for not outing a war widowed competitive shopper (Janet Leigh). Then they fall in love, because duh.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/39.jpg',
    title: 'The Dead',
    plot: 'Supposedly John Huston directed his final film while incapacitated &mdash; wheelchair, breathing tubes, the works. It doesn&#39;t look like it. Based on a James Joyce short story and starring his daughter Angelica Huston, The Dead casts a haunting spell over the screen, turning Christmas dinner into scorching drama',
    release: 1987,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/38.jpeg',
    title: 'Black Christmas ',
    plot: 'Because everything was getting a bit too peachy come Christmastime, Bob Clark smothered the holiday in the gruesome terror of the &#39;70s slasher flick. You&#39;ll want to remove that pointy star from the top of the tree after watching this one.',
    release: 1974,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/37.jpg',
    title: 'Bell, Book, and Candle',
    plot: 'Witches have Christmas problems too, you know. Kim Novak stars as a sorceress who risks losing her powers after casting a love spell on one of her gallery patrons (Jimmy Stewart). The best thing about this movie is that Novak&#39;s witch doesn&#39;t get away with it. Failure is rare in the picture perfect scenery of &#39;50s rom-coms.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/36.jpeg',
    title: 'Arthur Christmas',
    plot: 'Aardman Animation (Wallace &amp; Gromit) took a stab at CG animation and did what few other studios can ever achieve: heart. Their take on modern Christmas saddles Santa with the concept of going back to the basics, with his son Arthur as the remaining North Poler who finds joy in the holiday event.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/35.jpg',
    title: 'Trading Places',
    plot: 'I&#39;ll bet you $1 that there will never be a Christmas movie focused on Wall Street stock trading that&#39;s as funny as this Eddie Murphy/Dan Ackroyd comedy.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/34.jpg',
    title: 'Christmas in Connecticut',
    plot: 'No, not the 1992, Arnold Schwarzenegger-directed remake. Never that. The &#39;45 original is a romp of criss-crossing relationships and deceit, which goes down at every Christmas gathering, whether you know it or not.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/33.jpg',
    title: 'Bad Santa',
    plot: 'This could have gone horribly wrong &mdash; who wants to see Santa turned into a boozin&#39; sex-aholic? But juxtaposing iconography only works to the benefit of this sad sack story, despicable and gleefully Grinchy',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/a-christmas-carol-movie-poster-1951-1020427412.jpg',
    title: 'A Christmas Carol',
    plot: 'The no frills adaptation of Dickens&#39; story turned Alastair Sim into the definitive Ebenezer Scrooge. There&#39;s a colorized version of the film out there in the world, completely inferior to the sharp black &amp; white original.',
    release: 1951,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/MPW-25083.jpeg',
    title: 'Gremlins',
    plot: 'What if your present turned to pure evil? All it takes is the mention that Gizmo and the Gremlins are Christmas gifts to ignite Joe Dante&#39;s horror comedy with extra layer of flavor. There&#39;s never been an anti-materialism parable quite like this.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/30.jpg',
    title: 'Love Actually',
    plot: 'Little known fact: Richard Curtis&#39; Crash-esque Christmas romance can actually be tapped for syrup. It&#39;s that sappy. And it&#39;s impossible to turn off.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/29.png',
    title: 'We&#39;re No Angels',
    plot: 'One of Humphrey Bogart&#39;s few comedies, We&#39;re No Angels has a modern rhythm to it that would woo even those turned off by &ldquo;old&rdquo; movies (yes, they exist). It&#39;s a banter-fest as three escaped convicts learn to be nice guys once again',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/28.jpeg',
    title: 'Meet Me in St. Louis',
    plot: 'Judy Garland debuted the song &ldquo;Have Yourself a Merry Little Christmas&rdquo; in this romantic musical, which is just as much a love letter to the World&#39;s Fair as it is about men and women hooking up. Lame plotting aside, Garland is dazzling in the musical numbers and that&#39;s what really counts.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/27.jpeg',
    title: 'Eyes Wide Shut',
    plot: 'Christmas can be intoxicating, even without endless amounts of alcohol. Stanley Kubrick captures the holiday&#39;s mesmerizing ambiance in Eyes Wide Shut, a sexual odyssey fueled by desire and passion that all seems to stem from the December atmosphere.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/26.jpg',
    title: '8 Women',
    plot: 'Eight women, one murder, a house in the middle of nowhere. Swimming Pool director Fran&ccedil;ois Ozon delivers a musical Christmas version of Clue that&#39;s every bit as zany as one would hope.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/25.jpg',
    title: 'The Santa Clause',
    plot: 'Santa Clause preys on Tim Allen&#39;s history of &ldquo;masculinity.&rdquo; It takes his persona &mdash; too straight and narrow to ever believe in Christmas magic &mdash; and fluffs it up. There have likely been dissertations written on the choice to make the Jewish David Krumholtz Santa&#39;s #2, Bernard the Elf.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/24.jpeg',
    title: 'The Holly and The Ivy',
    plot: 'There&#39;s melancholia woven into the fabric of Christmas. For every person returning home to their loved ones, there&#39;s another who won&#39;t. The Holly and the Ivy captures that darkness. A family reunion unearths grief and, eventually, understanding',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/23.jpg',
    title: 'The Bishop&#39;s Wife',
    plot: 'The Whitney Houston remake The Preacher&#39;s Wife is OK, but the Cary Grant/Loretta Young/David Niven original is the right kind of Christian-themed Christmas story. It&#39;s one where Godly forces can&#39;t provide, because in the end, angels are still human. That&#39;s provocative &ndash; and easy to swallow with its cheery casing.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/22.png',
    title: 'The Shop Around the Corner',
    plot: 'Ernst Lubitsch&#39;s romantic comedy is a legitimately tense experience. We see Margaret Sullavan and Jimmy Stewart bickering with one another, knowing full well that they&#39;re in love with each other. It&#39;s a rom-com with stakes; will they actually get together? A question we never ask in the modern age.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/21_1.jpg',
    title: 'The Apartment',
    plot: 'Billy Wilder&#39;s classic comedy is rarely remembered for its Christmastime setting. The holiday looms in the background behind the down-on-his-luck Bud Baxter (Jack Lemmon), but it&#39;s essential to why he&#39;s able to change his life in the end.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/20_0.jpg',
    title: 'A Christmas Tale',
    plot: 'Family comedies arrive by the truckload during the holidays, but how rarely we find one that&#39;s reflective of real life get-togethers &mdash; frantic, grim, and even affirming',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/19_0.jpg',
    title: 'Meet John Doe',
    plot: 'Frank Capra can get away with anything &mdash; even a holiday-themed suicide movie. After penning a fake suicide note for the paper, a reporter searches for a John Doe to stand-in as the letter&#39;s author. He becomes a phenomenon as a man preaching in the name of the downtrodden &mdash; a 99%-er before that was even a thing.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/18_1.jpg',
    title: 'Die Hard',
    plot: 'The legacy of John McClane may be sullied by lame sequels, but his rampage through Nakatomi Plaza continues to kick ass and act as the perfect metaphor for the season. Christmas music plays, terrorists invade, and it all begins to feel a little like a family gathering.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/17_0.jpg',
    title: 'JoyeuxNo&euml;l',
    plot: 'Stretch that stirring battlefield truce scene from War Horse over two hours and you have the heartbreaking Christmas tale Joyeux No&euml;l. French, Scottish and German soldiers during World War I put down their guns for one night, just like you and your Republican cousins.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/16_0.jpg',
    title: 'Remember the Night',
    plot: 'This Barbara Stanwyck and Fred MacMurray romantic drama from 1940 is almost like 25th Hour, but with shoplifting and Christmas decorations. Stanwyck&#39;s character is inevitably going to jail, but her case has been postponed for Christmas. So MacMurray takes her and, without too much sentimentality, falls for her',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/15_0.jpg',
    title: 'Elf',
    plot: 'Only Will Ferrell, the master of manchildren, could create a character in the post-9/11 world with the earnestness to carry a Christmas movie. As goofy as Elf is, it&#39;s a delicate stunt to pull off and deserves the title of &ldquo;modern classic.&rdquo;',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/14_1.jpg',
    title: 'A Christmas Carol',
    plot: 'It&#39;s possible that this 75-year-old adaptation is more entertaining than it was back &#39;38. The imperfect black &amp; white and archaic stylings play directly into the Scrooge character. He&#39;s crotchety and the movie is kind of crotchety. The transportive quality is there &mdash; and it may not have upon its first release.',
    release: 1938,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/13_0.png',
    title: 'Dr. Seuss&#39; How the Grinch Stole Christmas!',
    plot: 'It&#39;s time to stop calling the animated adaptation of Dr. Seuss&#39; Christmas story a &ldquo;TV special.&rdquo; Looney Tunes had a Christmas special. Garfield had a Christmas special. Grinch is a special film, and Whos down in Whoville would agree that it&#39;s a vital part of the holiday, especially in the current age of snark.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/12_1.jpg',
    title: 'The Nightmare Before Christmas',
    plot: 'Let&#39;s clear this up: This is not a Halloween movie. It&#39;s about conformist Halloweeners breaking free of their chains to celebrate Christmas. Tim Burton and Henry Selick&#39;s macabre stop-motion film continues to be unique (and a top Hot Topic seller) 20 years later &ndash; and for good reason.',
    release: 1990,
    rating: 0,
}, {
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/11_2.jpg',
    title: 'Frosty the Snowman',
    plot: 'We&#39;re undoing Christmas cultural foundations here: The Rankin &amp; Bass &ldquo;specials&rdquo; are also films, animated shorts that have burned image:image:s of carol characters into our collective consciousness. Jackie Vernon turned Frosty into one of the most gosh darn lovable anthropomorphic creepsters in movie history. He might be a grown man who hangs out with children, but we love him.',
    release: 1990,
    rating: 0,
}, {
    title: 'A Charlie Brown Christmas',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/10_3.jpg',
    plot: 'Because it&#39;s the first of the Peanuts cartoons, Charlie Brown Christmas also deserves &ldquo;short film&rdquo; recognition. Even if religion doesn&#39;t factor into your Christmas, Charlie Brown, Linus, Snoopy and the rest of the gang&#39;s realization of the over-commercialization of the holiday serves as a timeless lesson melodically enhance by the Vince Guardaldi Trio. As an important adult once put it, &quot;WAH WAH WAH WAH WAMP WAH.&quot;',
    release: 1990,
    rating: 0,
}, {
    title: 'National Lampoon&#39;s Christmas Vacation',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/9_3.jpg',
    plot: 'Christmas is filled with joy and it&#39;s filled with nightmares. The third sequel to Vacation explores the latter. It&#39;s pitch perfect. The uproarious sewer explosion is something we all now wish on our most annoying family members. &quot;Merry Christmas, the shitter&#39;s full!&quot;',
    release: 1990,
    rating: 0,
}, {
    title: 'A Christmas Story',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/8_4.jpg',
    plot: 'Don&#39;t hate this movie because TBS insists on playing the movie for 24 hours straight. The cavalcade of familial horrors &mdash; that leg lamp, man &mdash; are still as punchy as ever. Being a kid sucks. A Christmas Story makes remembering that fact all OK.',
    release: 1990,
    rating: 0,
}, {
    title: 'Holiday Inn',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/7_5.jpg',
    plot: 'Before Irving Berlin repurposed &ldquo;White Christmas&rdquo; for the movie of the same name, it debuted in Holiday Inn, a musical romp that hits all its major beats on Christmas. The stars aligned for Holiday Inn, with Bing Crosby and Fred Astaire showing off their skills in full force',
    release: 1990,
    rating: 0,
}, {
    title: 'Home Alone',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/6_6.jpg',
    plot: 'Is it wrong that I still want to live a weekend by myself, Home Alone-style? Macaulay Culkin got his Christmas wish, eating ice cream and watching gangster movies while his parents lost their minds trying to get home over the holiday. It became our fantasy. Though the climax is what sells the movie &mdash; the epic Rube Goldberg death match between Kevin and the Wet Bandits &mdash; but every moment entertains. Kevin&#39;s preparation for the showdown set to &quot;Carol of the Bells&quot; is iconic.',
    release: 1990,
    rating: 0,
}, {
    title: 'Babes in Toyland',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/5_7.jpg',
    plot: 'Stan Laurel and Oliver Hardy&#39;s adventure through the fantasy world of Toyland may be one of the most uproarious movies of all time, Christmas-themed or not. You could plop the duo in a Judd Apatow movie today and their comedy would click &mdash; they&#39;re that universal. Surrounding them is pure imagination, with costumes and sets ranging from horrifying to goofy. Laurel and Hardy at the top of their game.',
    release: 1934,
    rating: 0,
}, {
    title: 'It&#39;s a Wonderful Life',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/4_11.jpg',
    plot: 'Many will say the Frank Capra classic is too far down on the list, even at #4. The truth is, the redemptive story of George Bailey (James Stewart) is a great movie, not a brilliant movie. It takes it&#39;s merry ol&#39; time getting to the juicy stuff, but when Bailey meets Clarence the Angel, the whirlwind of feelings begins',
    release: 1990,
    rating: 0,
}, {
    title: 'Rudolph the Red-Nosed Reindeer',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/3_10.jpg',
    plot: 'Though Rudolph&#39;s nose squeak is among the most heinous noises ever committed to film, the Rankin &amp; Bass stop-motion cartoon is heartwarming, cheerful, and downright bizarre. I don&#39;t know what recreational substances helped someone throw a dentist elf, misfit toys, and Burl Ives into one movie, but they did it and we&#39;re grateful.',
    release: 1990,
    rating: 0,
}, {
    title: 'The Muppet Christmas Carol',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/2.png',
    plot: 'The holidays are all about dropping cynicism to relish in the mushier spectrum of human emotion. The Muppets were born from those feelings. Pitting them against Michael Caine&#39;s Scrooge, who never misses a cue when talking down to his felt costars, reinvents the time-honored classic. The music by Paul Williams and the framework of Gonzo as Dickens is pure magic. Despite being lauded by Christmas movie fanatics, Muppet Christmas Carol is still underappreciated.',
    release: 1990,
    rating: 0,
}, {
    title: 'Miracle on 34th Street',
    image: 'http://20771u4biuu92ycq56s35ln19op.wpengine.netdna-cdn.com/wp-content/uploads/sites/5/uploads/scanner/1_12.jpg',
    plot: '</p>',
    release: ,
    rating: 0;
}];
