module.exports = {
  movie: [
    "<div class='row'>",
      "<div class='col-md-10'>",
        "<h3><%=title%></h3>",
      "</div>",
      "<div class='editMovie col-md-2' id='<%=_id%>'>",
        "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span>",
        "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span>",
      "</div>",
    "</div>",
    "<div class='row'>",
      "<div class='col-md-4'>",
        "<img src='<%=image%>' alt='<%=title%>'>",
      "</div>",
      "<div class='col-md-8'>",
        "<p class='plot'><%=description%></p>",
        "<span>  Released </span><p class='date'>",
        "<%=release%>",
        "</p>",
        "<span>Rating: </span><p class='rating'><%=rating%></p>",
      "</div>",
    "</div>",
  ].join(""),
  header: [
      "<h1>ALL THE CHRISTMAS MOVIES</h1>"
  ].join(""),
  footer: [
      "<h3>Created by Sally Kingston</h3>"
  ].join(""),
  form: [
    "<div class='btn-group' role='group' aria-label='...'>",
      "<button type='button' class='btn btn-success sort release'>Sort by Release Date</button>",
      "<button type='button' class='btn btn-danger sort rating'>Sort by Rating</button>",
    "</div>",
    "<h3>Add a Christmas Movie</h3>",
    "<form>",
      "<div class='form-group'>",
        "<label for='movieTitle'>Title</label>",
        "<input type='text' class='form-control' id='movieTitle' placeholder='Title'>",
      "</div>",
      "<div class='form-group'>",
        "<label for='movieDescription'>Description</label>",
        "<input type='text' class='form-control' id='movieDescription' placeholder='Description'>",
      "</div>",
      "<div class='form-group'>",
        "<label for='movieYear'>Release Year</label>",
        "<input type='text' class='form-control' id='movieYear' placeholder='2015'>",
      "</div>",
      "<div class='form-group'>",
        "<label for='movieRating'>Rating</label>",
        "<input type='text' class='form-control' id='movieRating' placeholder='1-5'>",
      "</div>",
      "<div class='form-group'>",
        "<label for='imageURL'>Image URL</label>",
        "<input type='text' class='form-control' id='imageURL' placeholder='.....'>",
      "</div>",
      "<button type='submit' class='btn btn-default' id='imageUploadSubmit'>Submit</button>",
    "</form>",
  ].join("")
}
